// 150 math (year 9+ level) + 150 Swedish multiple-choice questions
// Format: [questionText, optA, optB, optC, optD, correctIndex]

const mathQuestions = [
  // --- Algebra (1-25) ---
  ["Lös ekvationen: 3x − 7 = 2x + 5", "2", "5", "12", "19", 2],
  ["Lös: 4(x − 3) = 2x + 6", "3", "6", "9", "12", 2],
  ["Lös: (x + 4)/3 = 5", "1", "7", "11", "15", 2],
  ["Lös ekvationssystemet: x + y = 14, 2x − y = 1", "3 och 11", "5 och 9", "6 och 8", "7 och 7", 1],
  ["Lös: 2x² = 50", "5", "±5", "25", "±25", 1],
  ["Om f(x) = 3x − 5, vad är f(4)?", "2", "7", "12", "17", 1],
  ["Förenkla: (3x²y)²", "6x²y²", "9x²y²", "9x⁴y²", "3x⁴y²", 2],
  ["Faktorisera: x² − 5x + 6", "(x−1)(x−6)", "(x−2)(x−3)", "(x+2)(x+3)", "(x−6)(x+1)", 1],
  ["Lös: x² − 7x + 12 = 0", "3 och 4", "2 och 6", "−3 och −4", "1 och 12", 0],
  ["Utveckla: (2x − 3)²", "4x² + 9", "4x² − 6x + 9", "4x² − 12x + 9", "4x² − 12x − 9", 2],
  ["Lös olikheten: 2x + 1 > 7", "x > 3", "x < 3", "x ≥ 3", "x > 4", 0],
  ["Lös: 3x − 2 = 5x + 6", "−4", "−2", "2", "4", 0],
  ["Utveckla: (x + 5)(x − 3)", "x² + 2x − 15", "x² − 2x − 15", "x² + 2x + 15", "x² + 8x − 15", 0],
  ["Lös ekvationssystemet: 2x + y = 10, x − y = 2", "3 och 4", "4 och 2", "5 och 0", "6 och −2", 1],
  ["Förenkla: (x³)⁴", "x⁷", "x¹²", "x⁶⁴", "4x³", 1],
  ["y är proportionell mot x, och y = 12 när x = 3. Vad är y när x = 7?", "16", "21", "24", "28", 3],
  ["Lös: 1/x = 4", "4", "1/2", "1/4", "1/8", 2],
  ["Lös: x² − 16 = 0", "4", "±4", "16", "±16", 1],
  ["Förenkla: (6x²y) / (2xy²)", "3x/y", "3xy", "3y/x", "4x/y", 0],
  ["Lös: 5x + 3 = 2x + 15", "3", "4", "5", "6", 1],
  ["För vilket värde på x är 2x + 1 = 0?", "−1", "−1/2", "1/2", "1", 1],
  ["Lös: x/4 − x/6 = 1", "6", "8", "10", "12", 3],
  ["Om f(x) = x² + 1, vad är f(−3)?", "−8", "−10", "8", "10", 3],
  ["Lös: 2(x − 1) + 3(x + 2) = 24", "2", "3", "4", "5", 2],
  ["Vilket värde på x gör uttrycket x² − 4x + 4 lika med 0?", "0", "1", "2", "4", 2],

  // --- Potenser, rötter, talteori (26-45) ---
  ["Beräkna 2⁵ · 2³", "2⁸", "2¹⁵", "2²", "4⁸", 0],
  ["Vad är 10⁻² i decimalform?", "0,1", "0,01", "−100", "−20", 1],
  ["Förenkla: 5⁷ / 5⁴", "5³", "5¹¹", "5²", "125 000", 0],
  ["Skriv 5,4 · 10⁴ som vanligt tal.", "540", "5 400", "54 000", "540 000", 2],
  ["Skriv 0,00072 på grundpotensform.", "7,2 · 10³", "7,2 · 10⁻³", "7,2 · 10⁻⁴", "72 · 10⁻⁵", 2],
  ["Beräkna √121", "9", "11", "12", "60,5", 1],
  ["Beräkna √50 ungefär.", "5", "7,07", "12,5", "25", 1],
  ["Vad är kubikroten ur 27?", "3", "9", "13,5", "81", 0],
  ["Förenkla: √12 · √3", "3", "6", "9", "36", 1],
  ["Vad är (−2)⁴?", "−16", "−8", "8", "16", 3],
  ["Vilket av följande tal är irrationellt?", "√4", "√9", "√2", "√16", 2],
  ["Minsta gemensamma multipel av 12 och 18?", "6", "18", "36", "72", 2],
  ["Största gemensamma delare av 48 och 36?", "4", "6", "12", "18", 2],
  ["Vilket av följande tal är ett primtal?", "33", "39", "51", "53", 3],
  ["Skriv 72 som produkt av primtalsfaktorer.", "2 · 36", "2² · 3²", "2³ · 3²", "8 · 9", 2],
  ["Vad är −5 − (−8)?", "−13", "−3", "3", "13", 2],
  ["Vad är (−3)²?", "−9", "−6", "6", "9", 3],
  ["Om 2ⁿ = 64, vad är n?", "4", "5", "6", "7", 2],
  ["Beräkna √(3² + 4²)", "5", "7", "12", "25", 0],
  ["Förenkla: √75 / √3", "5", "15", "25", "75", 0],

  // --- Procent och proportion (46-65) ---
  ["Ett pris höjs med 25 % från 400 kr. Nytt pris?", "425 kr", "475 kr", "500 kr", "550 kr", 2],
  ["En vara kostade 800 kr och får 15 % rabatt. Nytt pris?", "660 kr", "680 kr", "720 kr", "785 kr", 1],
  ["Ett pris sjunker 20 % från 500 kr och höjs sedan 20 %. Slutpris?", "480 kr", "500 kr", "520 kr", "600 kr", 0],
  ["45 elever är 60 % av årskurs 9. Hur många går i åk 9?", "27", "60", "75", "90", 2],
  ["En aktie går upp 50 % och sedan ner 50 %. Om startpris 100 kr — slutpris?", "50 kr", "75 kr", "100 kr", "125 kr", 1],
  ["Bankkonto med 3 % årsränta. 5 000 kr efter 2 år med ränta på ränta?", "5 150 kr", "5 300 kr", "5 304,50 kr", "5 450 kr", 2],
  ["Ett pris höjs 10 % och ges sedan 10 % rabatt. Nettoförändring?", "±0 %", "−1 %", "+1 %", "−10 %", 1],
  ["I en klass på 30 är 18 tjejer. Andel pojkar?", "30 %", "40 %", "50 %", "60 %", 1],
  ["Ritning i skala 1:50. Ett rum är ritat som 6 cm. Verklig längd?", "1,2 m", "2 m", "3 m", "30 m", 2],
  ["Hur många procent är 3/8?", "24 %", "30 %", "37,5 %", "38 %", 2],
  ["En bil kostar 250 000 kr. Värdet sjunker 15 % per år. Värde efter 1 år?", "212 500 kr", "215 000 kr", "225 000 kr", "237 500 kr", 0],
  ["Bensinpriset höjs från 15 till 18 kr/L. Höjning i procent?", "15 %", "18 %", "20 %", "25 %", 2],
  ["Matmoms 12 % läggs på 625 kr. Totalpris?", "637,50 kr", "675 kr", "700 kr", "725 kr", 2],
  ["y är omvänt proportionell mot x, y = 6 när x = 4. Vad är y när x = 3?", "4,5", "6", "8", "12", 2],
  ["Karta i skala 1:25 000. Sträcka 4 cm motsvarar?", "100 m", "250 m", "1 km", "4 km", 2],
  ["20 % rabatt plus ytterligare 10 % på det redan rabatterade priset. Total rabatt?", "25 %", "28 %", "30 %", "32 %", 1],
  ["Recept för 4 personer kräver 240 g smör. Hur mycket för 7 personer?", "400 g", "420 g", "450 g", "480 g", 1],
  ["En fond ökade 40 % ett år och 25 % året efter. Samlad ökning?", "65 %", "70 %", "75 %", "80 %", 2],
  ["8 arbetare utför jobbet på 15 dagar. Hur lång tid för 12 arbetare i samma takt?", "8 dagar", "10 dagar", "12 dagar", "20 dagar", 1],
  ["Lön höjs från 28 000 till 30 800 kr. Höjning i procent?", "8 %", "10 %", "12 %", "28 %", 1],

  // --- Geometri (66-90) ---
  ["Rätvinklig triangel med katetrar 9 och 12. Hypotenusan?", "13", "14", "15", "21", 2],
  ["Rätvinklig triangel har hypotenusa 25 och en katet 7. Andra kateten?", "18", "20", "24", "32", 2],
  ["Area av cirkel med radie 6 cm (π ≈ 3,14).", "37,68 cm²", "56,52 cm²", "113,04 cm²", "452,16 cm²", 2],
  ["Omkrets av cirkel med diameter 14 cm (π ≈ 3,14).", "21,98 cm", "43,96 cm", "87,92 cm", "153,86 cm", 1],
  ["Volym av klot med radie 3 cm (V = 4πr³/3, π ≈ 3,14).", "37,68 cm³", "56,52 cm³", "113,04 cm³", "339,12 cm³", 2],
  ["Volym av pyramid med kvadratisk bas 6 × 6 och höjd 10.", "60", "120", "180", "360", 1],
  ["Två likformiga trianglar har skalfaktor 1:3. Förhållandet mellan deras areor?", "1:3", "1:6", "1:9", "1:27", 2],
  ["Volym av kon med radie 4 och höjd 9 (π ≈ 3,14).", "75,36", "113,04", "150,72", "452,16", 2],
  ["Vinkelsumman i en sexhörning?", "360°", "540°", "720°", "900°", 2],
  ["En yttervinkel i en triangel är 120°. Summan av de två motstående innervinklarna?", "60°", "90°", "120°", "180°", 2],
  ["Avståndet mellan punkterna (1, 2) och (4, 6) i ett koordinatsystem?", "3", "4", "5", "7", 2],
  ["Likbent triangel med bas 8 och ben 5. Arean?", "10", "12", "14", "20", 1],
  ["En kvadrat har diagonal 10. Hur lång är sidan?", "5", "7,07", "10", "14,14", 1],
  ["Mantelarea på cylinder med radie 3 och höjd 10 (π ≈ 3,14).", "94,2", "113,04", "188,4", "282,6", 2],
  ["Total ytarea av kub med sidan 4 cm.", "24 cm²", "48 cm²", "64 cm²", "96 cm²", 3],
  ["Regelbunden åttahörning. Innervinkel?", "108°", "120°", "135°", "144°", 2],
  ["Cirkelsektor med radie 6 och centrumvinkel 60° (π ≈ 3,14). Area?", "6,28", "18,84", "37,68", "113,04", 1],
  ["Area av en romb med diagonaler 8 och 6.", "14", "24", "48", "30", 1],
  ["Skala 1:200. En yta är 4 cm² på ritningen. Verklig area?", "0,8 m²", "8 m²", "16 m²", "80 m²", 2],
  ["I en rätvinklig triangel är två vinklar 90° och 35°. Tredje vinkeln?", "35°", "45°", "55°", "65°", 2],
  ["Mittpunktsvinkeln i en regelbunden sexhörning?", "45°", "60°", "72°", "90°", 1],
  ["sin(30°) = ?", "0,3", "0,5", "0,7", "1", 1],
  ["tan(45°) = ?", "0", "1/√2", "1", "√3", 2],
  ["I en rätvinklig triangel är hypotenusan motstående till den räta vinkeln. Om en katet är 5 och hypotenusan 13, är den andra kateten:", "8", "10", "12", "14", 2],
  ["Ytarea av ett klot med radie 5 (A = 4πr², π ≈ 3,14).", "157", "314", "523,6", "1 570", 1],

  // --- Räta linjens ekvation och funktioner (91-105) ---
  ["Räta linjen genom (0, 2) och (3, 8). k-värde (lutning)?", "1", "2", "3", "6", 1],
  ["Vad är m-värdet i y = 3x − 4?", "−4", "3", "4", "−3", 0],
  ["Var skär linjen y = −2x + 5 y-axeln?", "−5", "−2", "2", "5", 3],
  ["Vilken linje är parallell med y = 4x − 1?", "y = −4x + 2", "y = 4x + 3", "y = x − 1", "y = −x/4", 1],
  ["Vilken linje är vinkelrät mot y = 2x + 1?", "y = 2x − 1", "y = −2x + 1", "y = −x/2 + 3", "y = x/2 + 3", 2],
  ["Räta linjen genom (1, 1) och (3, 7)?", "y = 3x − 2", "y = 2x − 1", "y = 3x + 2", "y = x + 4", 0],
  ["För vilket x är y = 0 i linjen y = 2x − 8?", "−4", "−2", "2", "4", 3],
  ["f(x) = ax + b. Om f(1) = 5 och f(3) = 11, vad är a?", "2", "3", "4", "6", 1],
  ["Skärningspunkten mellan y = 2x + 1 och y = −x + 7?", "(1, 3)", "(2, 5)", "(3, 7)", "(4, 9)", 1],
  ["Var skär y = x² − 4 x-axeln?", "x = ±2", "x = ±4", "x = 2", "x = −4", 0],
  ["Funktionen f(x) = x² har minimum i?", "x = −1", "x = 0", "x = 1", "inget minimum", 1],
  ["Räta linjen med k = 0 som passerar (0, 3)?", "y = 0", "y = 3", "x = 3", "y = 3x", 1],
  ["k-värdet för linjen genom (0, 0) och (2, 3)?", "2/3", "1", "3/2", "2", 2],
  ["För linjen y = −3x + 6 — när är y > 0?", "x < 2", "x > 2", "x < 6", "x > 6", 0],
  ["Vilken av följande funktioner är en konstant?", "y = 2x", "y = x + 2", "y = 4", "y = x²", 2],

  // --- Statistik och sannolikhet (106-120) ---
  ["Medelvärde av 4, 7, 9, 10, 15?", "7", "8", "9", "10", 2],
  ["Median av 3, 5, 8, 10, 14?", "5", "8", "10", "14", 1],
  ["Typvärdet av 2, 3, 3, 4, 5, 5, 5, 6?", "3", "4", "5", "6", 2],
  ["Sannolikheten att få en sexa vid ett tärningskast?", "1/2", "1/3", "1/6", "1/12", 2],
  ["Sannolikhet att få krona två gånger i rad med ett mynt?", "1/2", "1/3", "1/4", "1/8", 2],
  ["Sannolikhet att dra ett ess ur en hel kortlek (52 kort)?", "1/4", "1/13", "1/26", "1/52", 1],
  ["Medelvärdet av fyra tal är 12. Tre av dem är 10, 11 och 14. Det fjärde?", "11", "12", "13", "14", 2],
  ["2 av 5 väljare röstar på parti A, vilket ger 60 röster. Totalt antal röster?", "100", "120", "150", "300", 2],
  ["En påse har 3 röda och 5 blå kulor. Sannolikhet att dra röd?", "1/3", "3/5", "3/8", "5/8", 2],
  ["Två tärningar kastas. Sannolikhet att summan blir 7?", "1/12", "1/8", "1/6", "1/4", 2],
  ["Median av 1, 2, 4, 5?", "2,5", "3", "3,5", "4", 1],
  ["Standardavvikelse är ett mått på?", "medelvärde", "median", "typvärde", "spridning", 3],
  ["Sannolikhet att få minst en sexa vid två tärningskast?", "1/6", "1/3", "11/36", "1/36", 2],
  ["Fyra olika kläder och tre par skor. Antal kombinationer?", "7", "12", "16", "24", 1],
  ["Antal sätt att arrangera 4 personer i en rad?", "12", "16", "24", "64", 2],

  // --- Problemlösning (121-150) ---
  ["Ett rektangulärt rum har area 24 m² och längden 6 m. Omkretsen?", "10 m", "14 m", "20 m", "24 m", 2],
  ["Tre efterföljande heltal summerar till 57. Vilka är de?", "17, 18, 19", "18, 19, 20", "19, 20, 21", "20, 21, 22", 1],
  ["Två personer delar 180 kr i förhållandet 3:5. Mindre delen?", "60 kr", "67,50 kr", "72 kr", "80 kr", 1],
  ["En bil kör 90 km/h i 2 h 20 min. Körd sträcka?", "180 km", "195 km", "210 km", "225 km", 2],
  ["Två fartyg 500 km isär möts efter 5 h; ena kör 40 km/h snabbare. Deras hastigheter?", "30 och 70 km/h", "40 och 60 km/h", "50 och 50 km/h", "20 och 80 km/h", 0],
  ["I en klass är 3/5 tjejer. Om 4 tjejer slutar blir fördelningen 1:1. Hur många elever från början?", "16", "18", "20", "24", 2],
  ["Kran A fyller en pool på 6 h och kran B på 3 h. Tid tillsammans?", "1 h 30 min", "2 h", "2 h 30 min", "4 h", 1],
  ["Ett pris sänks 30 %. Hur många procent måste det sedan höjas för att återställa originalpriset?", "30 %", "35 %", "40 %", "cirka 43 %", 3],
  ["Summan av två tal är 28 och deras differens är 4. Deras produkt?", "144", "180", "192", "210", 2],
  ["Rektangulärt fält med omkrets 60 m och längd dubbelt så stor som bredden. Area?", "100 m²", "150 m²", "200 m²", "300 m²", 2],
  ["En hjord: 24 kor, 36 får, 12 grisar. Centrumvinkel för grisar i ett cirkeldiagram?", "30°", "45°", "60°", "72°", 2],
  ["Anton köper 3 äpplen och 2 bananer för 60 kr. Bo köper 5 äpplen och 4 bananer för 110 kr. Pris per äpple?", "8 kr", "10 kr", "12 kr", "15 kr", 1],
  ["En kon (radie 3, höjd 12) töms i en cylinder med radie 3. Hur högt fylls cylindern?", "3", "4", "6", "12", 1],
  ["Om x² + x = 20 och x > 0, vilket är x?", "2", "3", "4", "5", 2],
  ["Anna och Beatrice cyklar mot varandra från 60 km isär. 12 km/h respektive 18 km/h. Tid tills mötet?", "1,5 h", "2 h", "2,5 h", "3 h", 1],
  ["Kalle har dubbelt så mycket pengar som Lisa. Efter att Kalle gett 20 kr till Lisa har de lika mycket. Hur mycket hade Kalle från början?", "40 kr", "60 kr", "80 kr", "100 kr", 2],
  ["En regelbunden tolvhörning. Hur stor är varje innervinkel?", "120°", "135°", "150°", "162°", 2],
  ["En bil förbrukar 6,5 L per 100 km. Hur mycket bränsle går det åt för 340 km?", "19,5 L", "22,1 L", "24,5 L", "26 L", 1],
  ["Om a : b = 2 : 3 och b : c = 4 : 5, vad är a : c?", "2 : 5", "6 : 15", "8 : 15", "10 : 15", 2],
  ["En tank rymmer 800 L. Kran A fyller 20 L/min, kran B 30 L/min. Tid att fylla tillsammans?", "12 min", "14 min", "16 min", "20 min", 2],
  ["Ett tåg 150 m passerar en perrong på 250 m med 72 km/h. Tid?", "10 s", "15 s", "20 s", "25 s", 2],
  ["En plånbok har bara 10- och 20-kronorsedlar, totalt 13 sedlar värda 200 kr. Antal 20-kronorsedlar?", "5", "6", "7", "8", 2],
  ["En sträcka på 120 km körs i 60 km/h och nästa 120 km i 80 km/h. Medelhastighet?", "65 km/h", "68,6 km/h", "70 km/h", "72 km/h", 1],
  ["En kvadrat är inskriven i en cirkel med radie 5. Kvadratens area?", "25", "50", "75", "100", 1],
  ["En låda har 3 vokaler och 5 konsonanter (8 bokstäver). Sannolikhet att dra två vokaler utan återläggning?", "3/28", "3/16", "1/4", "5/28", 0],
  ["En stege är 3 m lång. Den står 1,8 m upp på en vägg. Hur långt från väggen står foten?", "1,2 m", "1,8 m", "2,0 m", "2,4 m", 3],
  ["Vinst 25 % på ett inköpspris på 240 kr. Försäljningspris?", "265 kr", "285 kr", "300 kr", "320 kr", 2],
  ["Anna kör 60 km på 45 min. Medelhastighet?", "60 km/h", "70 km/h", "80 km/h", "90 km/h", 2],
  ["En romb har area 54 och en diagonal 9. Andra diagonalen?", "6", "9", "12", "18", 2],
  ["Om x = a² − b², a = 7 och b = 4, vad är x?", "11", "15", "33", "49", 2],
];

const swedishQuestions = [
  // ===== Ordkunskap, HP-nivå (1-100) =====
  ["'Fördragsam' betyder ungefär?", "Otålig", "Tålmodig", "Stingslig", "Kategorisk", 1],
  ["'Lakonisk' betyder ungefär?", "Pratsam", "Kortfattad", "Förvirrad", "Omständlig", 1],
  ["'Sporadisk' betyder ungefär?", "Ständig", "Tillfällig", "Tilltagande", "Noggrann", 1],
  ["'Kategorisk' betyder ungefär?", "Tveksam", "Bestämd", "Omtänksam", "Orolig", 1],
  ["'Benägen' betyder ungefär?", "Ovillig", "Villig", "Ängslig", "Avundsjuk", 1],
  ["'Förmäten' betyder ungefär?", "Ödmjuk", "Övermodig", "Blyg", "Försiktig", 1],
  ["'Ålderstigen' betyder ungefär?", "Ung", "Mycket gammal", "Mogen", "Rutinerad", 1],
  ["'Inbilsk' betyder ungefär?", "Blygsam", "Självgod", "Fundersam", "Godtrogen", 1],
  ["'Bräddfull' betyder ungefär?", "Halvfull", "Fylld till bredden", "Tom", "Överfull spill", 1],
  ["'Skarpsinnig' betyder ungefär?", "Slö", "Klartänkt", "Ytlig", "Envis", 1],
  ["'Skrupler' betyder ungefär?", "Ursäkter", "Samvetsbetänkligheter", "Krav", "Rykten", 1],
  ["'Oförställd' betyder ungefär?", "Förvrängd", "Oförfalskad", "Överdriven", "Blyg", 1],
  ["'Tentativ' betyder ungefär?", "Slutgiltig", "Preliminär", "Självklar", "Direkt", 1],
  ["'Rigid' betyder ungefär?", "Smidig", "Stel", "Hastig", "Opartisk", 1],
  ["'Obskyr' betyder ungefär?", "Upplyst", "Oklar", "Välkänd", "Självklar", 1],
  ["'Svärmisk' betyder ungefär?", "Nyktert saklig", "Drömmande", "Forsk", "Misstroisk", 1],
  ["'Försmädlig' betyder ungefär?", "Tröstande", "Hånfull", "Mild", "Pratglad", 1],
  ["'Skadeglad' betyder ungefär?", "Medkännande", "Glad åt andras olycka", "Upprymd", "Sorgsen", 1],
  ["'Förklenande' betyder ungefär?", "Upphöjande", "Nedsättande", "Neutral", "Uppskattande", 1],
  ["'Kverulans' betyder ungefär?", "Uppmuntran", "Gnäll", "Beröm", "Tystnad", 1],
  ["'Makaber' betyder ungefär?", "Rolig", "Kuslig", "Normal", "Lättsam", 1],
  ["'Stingslig' betyder ungefär?", "Lugn", "Lättretad", "Vänlig", "Stolt", 1],
  ["'Grassera' betyder ungefär?", "Avta", "Härja", "Undgå", "Lugna", 1],
  ["'Malplacerad' betyder ungefär?", "Lämplig", "Olämplig", "Passande", "Tillfällig", 1],
  ["'Kontemplativ' betyder ungefär?", "Impulsiv", "Begrundande", "Högljudd", "Pratsam", 1],
  ["'Flegmatisk' betyder ungefär?", "Häftig", "Oberörd", "Upphetsad", "Ängslig", 1],
  ["'Habil' betyder ungefär?", "Oskicklig", "Skicklig", "Lat", "Sträng", 1],
  ["'Latent' betyder ungefär?", "Utbruten", "Dold men möjlig", "Förbrukad", "Tydlig", 1],
  ["'Kausal' betyder ungefär?", "Tillfällig", "Orsaksbetingad", "Slumpmässig", "Likgiltig", 1],
  ["'Prudentlig' betyder ungefär?", "Vild", "Pryd", "Slapp", "Djärv", 1],
  ["'Indolent' betyder ungefär?", "Flitig", "Slö", "Snabb", "Intensiv", 1],
  ["'Infam' betyder ungefär?", "Hederlig", "Skamlig", "Snäll", "Smickrande", 1],
  ["'Jämbördig' betyder ungefär?", "Underlägsen", "Likvärdig", "Överlägsen", "Annorlunda", 1],
  ["'Kakofoni' betyder ungefär?", "Harmoni", "Oljud", "Ton", "Tystnad", 1],
  ["'Floskel' betyder ungefär?", "Sanning", "Tom fras", "Berättelse", "Anekdot", 1],
  ["'Gehör' betyder ungefär?", "Osäker bedömning", "Öra för något", "Missuppfattning", "Tonart", 1],
  ["'Hybrid' betyder ungefär?", "Ren form", "Blandning", "Motpart", "Undantag", 1],
  ["'Impulsiv' betyder ungefär?", "Eftertänksam", "Hastig", "Planerad", "Lugn", 1],
  ["'Inbunden' (om person) betyder ungefär?", "Utåtriktad", "Tillbakadragen", "Hjälpsam", "Nyfiken", 1],
  ["'Indignerad' betyder ungefär?", "Uppriktigt upprörd", "Berörd", "Likgiltig", "Full", 0],
  ["'Konvergera' betyder ungefär?", "Skiljas åt", "Närma sig varandra", "Vägra", "Ignorera", 1],
  ["'Kryptisk' betyder ungefär?", "Tydlig", "Gåtfull", "Logisk", "Direkt", 1],
  ["'Kvasi' betyder ungefär?", "Äkta", "Skenbar", "Helt sann", "Giltig", 1],
  ["'Lansera' betyder ungefär?", "Dra tillbaka", "Introducera", "Sabotera", "Avbryta", 1],
  ["'Luminös' betyder ungefär?", "Mörk", "Lysande", "Dunkel", "Matt", 1],
  ["'Misär' betyder ungefär?", "Välstånd", "Armod", "Glädje", "Lugn", 1],
  ["'Neutral' betyder ungefär?", "Partisk", "Opartisk", "Fientlig", "Inblandad", 1],
  ["'Obestridlig' betyder ungefär?", "Omstridd", "Otvivelaktig", "Diskutabel", "Oklar", 1],
  ["'Pretentiös' betyder ungefär?", "Ödmjuk", "Högtravande", "Enkel", "Uppriktig", 1],
  ["'Prosaisk' betyder ungefär?", "Poetisk", "Alldaglig", "Upphöjd", "Dramatisk", 1],
  ["'Reservation' betyder ungefär?", "Fullt instämmande", "Förbehåll", "Bekräftelse", "Invändningslöshet", 1],
  ["'Resignera' betyder ungefär?", "Kämpa på", "Ge upp", "Förneka", "Kämpa emot", 1],
  ["'Rigorös' betyder ungefär?", "Mild", "Sträng", "Ytlig", "Likgiltig", 1],
  ["'Suverän' betyder ungefär?", "Underlägsen", "Överlägsen", "Lika", "Oförmögen", 1],
  ["'Tendentiös' betyder ungefär?", "Opartisk", "Partisk", "Välunderbyggd", "Saklig", 1],
  ["'Tillförlitlig' betyder ungefär?", "Opålitlig", "Pålitlig", "Tveksam", "Skakig", 1],
  ["'Vederlägga' betyder ungefär?", "Bekräfta", "Motbevisa", "Anta", "Förstärka", 1],
  ["'Oförvitlig' betyder ungefär?", "Klandervärd", "Klanderfri", "Tvivelaktig", "Uselt", 1],
  ["'Vederkvickande' betyder ungefär?", "Tröttsam", "Uppfriskande", "Förbryllande", "Enformig", 1],
  ["'Försagd' betyder ungefär?", "Djärv", "Blyg", "Modig", "Argumenterande", 1],
  ["'Jovialisk' betyder ungefär?", "Tvär", "Gladlynt", "Sträng", "Tystlåten", 1],
  ["'Omstörtande' betyder ungefär?", "Bevarande", "Revolutionerande", "Ordnande", "Tillfällig", 1],
  ["'Introspektion' betyder ungefär?", "Utåtriktad aktivitet", "Självbetraktelse", "Granskning av andra", "Undersökning", 1],
  ["'Ymnig' betyder ungefär?", "Knapp", "Riklig", "Sparsam", "Liten", 1],
  ["'Grannlaga' (om situation) betyder ungefär?", "Enkel", "Känslig", "Obetydlig", "Formell", 1],
  ["'Morbid' betyder ungefär?", "Livsbejakande", "Sjuklig", "Avslappnad", "Munter", 1],
  ["'Monoton' betyder ungefär?", "Omväxlande", "Enformig", "Livfull", "Flerfärgad", 1],
  ["'Kuriös' betyder ungefär?", "Alldaglig", "Underlig", "Vanlig", "Logisk", 1],
  ["'Inskränkt' (om person) betyder ungefär?", "Vidsynt", "Trångsynt", "Nyfiken", "Bildad", 1],
  ["'Kräsen' betyder ungefär?", "Lättillfredsställd", "Nogräknad", "Tacksam", "Snäll", 1],
  ["'Ömklig' betyder ungefär?", "Imponerande", "Ynklig", "Kraftfull", "Stolt", 1],
  ["'Despotisk' betyder ungefär?", "Demokratisk", "Tyrannisk", "Mild", "Förhandlande", 1],
  ["'Försumbar' betyder ungefär?", "Viktig", "Obetydlig", "Avgörande", "Oförglömlig", 1],
  ["'Enträgen' betyder ungefär?", "Försiktig", "Ivrig", "Tvekande", "Lat", 1],
  ["'Vedermöda' betyder ungefär?", "Belöning", "Prövning", "Lätt arbete", "Seger", 1],
  ["'Futtig' betyder ungefär?", "Storslagen", "Obetydlig", "Frikostig", "Vacker", 1],
  ["'Tvetydig' betyder ungefär?", "Entydig", "Dubbeltydig", "Tydlig", "Tvärsäker", 1],
  ["'Ovidkommande' betyder ungefär?", "Relevant", "Irrelevant", "Avgörande", "Övertygande", 1],
  ["'Obeveklig' betyder ungefär?", "Eftergiven", "Orubblig", "Vacklande", "Mild", 1],
  ["'Vanvördig' betyder ungefär?", "Respektfull", "Respektlös", "Försiktig", "Tveksam", 1],
  ["'Tillstymmelse' betyder ungefär?", "Överflöd", "Antydan", "Stor mängd", "Helhet", 1],
  ["'Förträfflig' betyder ungefär?", "Medelmåttig", "Utmärkt", "Undermålig", "Märklig", 1],
  ["'Ranglig' betyder ungefär?", "Stadig", "Ostadig", "Hård", "Ljus", 1],
  ["'Genomgripande' betyder ungefär?", "Ytlig", "Djupgående", "Undvikande", "Tillfällig", 1],
  ["'Avog' betyder ungefär?", "Vänlig", "Fientlig", "Nyfiken", "Likgiltig", 1],
  ["'Försynt' betyder ungefär?", "Påträngande", "Hövlig", "Högljudd", "Självhävdande", 1],
  ["'Outtröttlig' betyder ungefär?", "Snabbt trött", "Energisk", "Rastlös", "Sömnig", 1],
  ["'Hänsynslös' betyder ungefär?", "Omtänksam", "Brutal", "Empatisk", "Förlåtande", 1],
  ["'Aningslös' betyder ungefär?", "Välinformerad", "Ovetande", "Insatt", "Klartänkt", 1],
  ["'Kuva' betyder ungefär?", "Uppmuntra", "Betvinga", "Befria", "Uppmärksamma", 1],
  ["'Nitisk' betyder ungefär?", "Slarvig", "Flitig", "Okoncentrerad", "Blyg", 1],
  ["'Dröjsmål' betyder ungefär?", "Hast", "Försening", "Punktlighet", "Avbokning", 1],
  ["'Vedersakare' betyder ungefär?", "Medhjälpare", "Motståndare", "Anhängare", "Främling", 1],
  ["'Spefull' betyder ungefär?", "Uppriktig", "Hånfull", "Uppmuntrande", "Vemodig", 1],
  ["'Klentrogen' betyder ungefär?", "Godtrogen", "Skeptisk", "Entusiastisk", "Övertygad", 1],
  ["'Olidlig' betyder ungefär?", "Behaglig", "Outhärdlig", "Tillfällig", "Mjuk", 1],
  ["'Förbryllad' betyder ungefär?", "Säker", "Förvirrad", "Argumenterande", "Fokuserad", 1],
  ["'Fyndig' (om replik) betyder ungefär?", "Trög", "Uppfinningsrik", "Rudimentär", "Oväsentlig", 1],
  ["'Frapperande' betyder ungefär?", "Oansenlig", "Slående", "Normal", "Lugnande", 1],
  ["'Ansenlig' betyder ungefär?", "Obetydlig", "Betydande", "Normal", "Oklar", 1],

  // ===== Grammatik: böjning och syntax (101-115) =====
  ["Pluralformen av 'barn'?", "barn", "barner", "barnar", "barnen", 0],
  ["Pluralformen av 'hus'?", "hus", "husar", "husor", "husen", 0],
  ["Pluralformen av 'äpple'?", "äpplen", "äpplor", "äpplar", "äppler", 0],
  ["Preteritum (imperfekt) av 'gå'?", "går", "gick", "gått", "gådde", 1],
  ["Perfekt av 'springa'?", "har spring", "har sprang", "har sprungit", "har springt", 2],
  ["Bestämd form singular av 'en bok'?", "boka", "boken", "bokar", "boket", 1],
  ["Imperativ (uppmaning) av 'springa'?", "Springa!", "Spring!", "Sprang!", "Sprungit!", 1],
  ["Vilken form har 'honom' i 'Jag såg honom'?", "Subjektsform", "Objektsform", "Genitiv", "Possessiv", 1],
  ["Komparativ av 'stor'?", "stor", "större", "störst", "storare", 1],
  ["Superlativ av 'bra'?", "bättre", "bäst", "bra", "godast", 1],
  ["Komparativ av 'ung'?", "ungare", "yngre", "ungast", "unga", 1],
  ["Vilken mening är grammatiskt korrekt?", "Hon kommit hem tidigt", "Hon kom tidigt hem", "Hon har kom hem", "Hon kom har hem", 1],
  ["Presens av 'vara'?", "var", "är", "varit", "blir", 1],
  ["Supinum av 'göra'?", "gör", "gjorde", "gjort", "göra", 2],
  ["Vilken meningsbyggnad är korrekt?", "Igår jag såg en film", "Igår såg jag en film", "Igår var film sett av mig", "Jag igår såg en film", 1],

  // ===== Idiom (faktiska svenska uttryck) (116-125) =====
  ["Vad betyder 'slå två flugor i en smäll'?", "Göra två saker samtidigt", "Misslyckas två gånger", "Vara våldsam", "Arbeta snabbt", 0],
  ["Vad betyder 'gå som katten kring het gröt'?", "Tala rakt ut", "Undvika att ta upp något", "Vara hungrig", "Arbeta noggrant", 1],
  ["Vad betyder 'kasta pärlor för svin'?", "Slösa något värdefullt på fel mottagare", "Ge bort gåvor", "Vara girig", "Förhandla dåligt", 0],
  ["Vad betyder 'ta det med en nypa salt'?", "Ta något bokstavligt", "Vara skeptisk mot något", "Bli arg", "Krydda något", 1],
  ["Vad betyder 'knyta näven i fickan'?", "Vara glad", "Undertrycka ilska", "Gömma pengar", "Vara tålmodig", 1],
  ["Vad betyder 'falla mellan stolarna'?", "Bli bortglömd eller missad", "Snubbla", "Sitta illa", "Byta åsikt", 0],
  ["Vad betyder 'ha hjärtat på rätt ställe'?", "Vara fysiskt frisk", "Vara god och välmenande", "Vara modig", "Vara förälskad", 1],
  ["Vad betyder 'hålla tummarna'?", "Vara nervös", "Önska någon lycka till", "Vara försiktig", "Hålla tyst", 1],
  ["Vad betyder 'i grevens tid'?", "Alldeles för sent", "I absolut sista stund", "Väldigt tidigt", "Aldrig", 1],
  ["Vad betyder 'det ligger en hund begraven'?", "Det finns något misstänkt bakom", "Någon är död", "Något är slut", "Något är gömt på marken", 0],

  // ===== Läsförståelse och ord i sammanhang (126-150) =====
  ["'Resonemanget haltar på flera punkter.' Vad betyder 'haltar' här?", "Rör sig framåt", "Har brister", "Är övertygande", "Går fort", 1],
  ["'Hon är såld på idén.' Vad betyder det?", "Hon säljer idén vidare", "Hon är helt övertygad", "Hon har avvisat den", "Hon sover", 1],
  ["'Trots regnet gick jag ut.' Vad betyder 'trots'?", "På grund av", "Även om det regnade", "I stället för", "När", 1],
  ["'Projektet gick om intet.' Vad betyder uttrycket?", "Projektet blev framgångsrikt", "Projektet misslyckades", "Projektet fortsatte", "Projektet startade om", 1],
  ["'Av och till reagerar han trotsigt.' Vad betyder 'av och till'?", "Aldrig", "Ibland", "Alltid", "Snart", 1],
  ["'Hennes argumentation är inte alltid konsekvent.' Vad betyder 'konsekvent'?", "Motsägelsefull", "Följdriktig", "Högljudd", "Detaljerad", 1],
  ["'De motstridiga rapporterna försvårar bedömningen.' Vad betyder 'motstridiga'?", "Samstämmiga", "Varandra motsägande", "Noggranna", "Snabba", 1],
  ["'Förslaget blev antaget med acklamation.' Vad betyder 'med acklamation'?", "Utan votering, genom tillrop", "Efter lång debatt", "Med minsta möjliga marginal", "Mot styrelsens vilja", 0],
  ["'Hon talade i obestämda ordalag om planen.' Vad betyder 'obestämda ordalag'?", "Mycket detaljerat", "Vagt och oprecist", "Arg", "Skriftligt", 1],
  ["'Utvecklingen har stagnerat.' Vad betyder 'stagnerat'?", "Accelererat", "Stannat av", "Vänt tillbaka", "Spridits", 1],
  ["'Artikeln är fri från värdeomdömen.' Vad betyder 'värdeomdömen'?", "Prisuppgifter", "Subjektiva bedömningar", "Hänvisningar", "Tekniska termer", 1],
  ["'Debatten var tillspetsad.' Vad betyder 'tillspetsad'?", "Avslappnad", "Hård och konfrontativ", "Kort", "Osaklig men rolig", 1],
  ["'Hon ansåg kritiken obefogad.' Vad betyder 'obefogad'?", "Välgrundad", "Utan giltig grund", "Välkommen", "Mild", 1],
  ["'Hans påstående står i diametral motsättning till mitt.' Vad betyder 'diametral'?", "Liknande", "Fullständigt motsatt", "Svagt avvikande", "Godtagbar", 1],
  ["'Förslaget är idag gångbart.' Vad betyder 'gångbart'?", "Förkastat", "Genomförbart och accepterat", "Fotgängbart", "Föråldrat", 1],
  ["'Konsekvenserna är överhängande.' Vad betyder 'överhängande'?", "Långt borta", "Nära förestående", "Oklara", "Avklarade", 1],
  ["'Hennes röst hade en uppfordrande ton.' Vad betyder 'uppfordrande'?", "Vädjande", "Pockande, krävande", "Glad", "Försiktig", 1],
  ["'Uppsatsen är späckad med exempel.' Vad betyder 'späckad'?", "Tom", "Fullproppad", "Komplicerad", "Kort", 1],
  ["'Hans tal var tillgjort.' Vad betyder 'tillgjort'?", "Uppriktigt", "Onaturligt och förställt", "Välformulerat", "Snabbt", 1],
  ["'Hon uttalade sig i svepande ordalag.' Vad betyder 'svepande'?", "Generaliserande", "Mycket exakt", "Kort", "Sorgset", 0],
  ["'Författarens analys är djuplodande.' Vad betyder 'djuplodande'?", "Ytlig", "Djupgående", "Felaktig", "Kortfattad", 1],
  ["'Meningen är övertydlig.' Vad betyder 'övertydlig'?", "Otydlig", "Så tydlig att det nästan blir löjligt", "Oklar", "Översatt", 1],
  ["'Hans omdöme är ovederhäftigt.' Vad betyder 'ovederhäftigt'?", "Tillförlitligt", "Inte att lita på", "Sakligt", "Tydligt", 1],
  ["'Han gav ett lakoniskt svar.' Vad betyder 'lakoniskt' här?", "Utförligt", "Kort och koncist", "Otrevligt", "Långrandigt", 1],
  ["'Uttalandet mottogs med ovationer.' Vad betyder 'ovationer'?", "Buanden", "Jubel och applåder", "Tystnad", "Frågor", 1],
];

window.QUESTIONS = {
  math: mathQuestions,
  swedish: swedishQuestions,
};
